os: windows
language: cpp
services: docker

branches:
  only:
  - master

stages:
- name: tar-1
- name: tar-2
- name: xz

before_install:
- export m_tools_directory_path="$(pwd)/tools"
- m_python3_directory_normal_path="/tmp/build/python3"
- export m_python3_path="${m_python3_directory_normal_path}/python.exe"
- mkdir -p "/tmp/build/output" "/tmp/build/assets" "${m_python3_directory_normal_path}"
- m_python3_directory_ugly_path=$(cd "${m_python3_directory_normal_path}" && cmd.exe /c 'echo %cd%' | tail -n 1)
- choco install python3 --confirm --params /InstallDir:"${m_python3_directory_ugly_path}"
- '"${m_python3_path}" -m pip install --upgrade pip'
- export m_git_tag=`git tag --list --points-at HEAD | head -n 1`
- if test -z "${m_git_tag}"; then export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}; else export TRAVIS_TAG="${m_git_tag}"; fi

before_deploy:
- git config --local user.name "p5-vbnekit"
- git config --local user.email "vbnekit@p5y.su"
- if test -z "${m_git_tag}"; then git tag -a "${TRAVIS_TAG}" -m "${TRAVIS_TAG}"; fi
- cd /tmp/build/assets
- 'while true; do sleep 300; echo "this message had to be sent, otherwise travis-ci will stop the deployment of large files by 10min timeout..."; done & export m_deploy_ping_pid=$!'

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: usn89BK6M+WmF1OjqCr+o+M7lTFhrPa8FLCfDoddwdT9ecbhQ7tEI4/CePyFIu5FUNdgFY++YeHv9MhzPdFo5UkfRP/RMWGtO6AKN5I+VOPZSf16xcXRhXiEgpA8Lr5l9Yf+KfSohVJNZj+iUGWqtS3hbKb/h57OP5jawMUYiS44/2++Xj6vY+Teq26+5njOY94nW7xfhreH1Xj0cObmPMlJPml8nj3A6M4HaJdUWuuv2c+osOzzX8dSOvaFDNdH7Am6QAo1GI4bQvyJmfpNf6peGPjv048bfPP/iU4otxSSIucpUHmp1TjXi6wtMeIxt7FFwFHe86lOVFzGQWat0DpZM7dad+vDTJVVhJH8vDN4hbY6FKQIOyEOUtiej4t/CCd4PaNrOGsDFl8jYY/I43Z/0aQqImQlfEtsgdc8Kozc+pku8xNGK23FNoMif9Mb1XnANz3tG+TpAuHOmoK5wuyjqDF8WBzL7ISt+QDeVRtgnlgEnvCpklaLsddgv41Gi76oJ5xU3cm3hKlEWiD6PtMWLFJnXMFISp6rrst0SdsoK/kGZbHX5PXxSg27yfIeWYAsSssZAJM7tXuhmGI5WOnY1mQKwH61lisYLY1uncOTrBiqX59FzpyYRvnh9KZuChAa163JRzKlYh5bmbxNPpoMm+Gliv461W7NaPQQwzM=
  file_glob: true
  file: "*"
  on:
    branch: master

after_deploy: 'kill ${m_deploy_ping_pid}'

jobs:
  include:
  - name: chocolatey
    stage: tar-1
    script: |
      "${m_python3_path}" "${m_tools_directory_path}/travis_wait_alternative.py" sh -e << EOF
      export PS4="executing command: "; set -x
      docker build --tag chocolatey --file chocolatey.Dockerfile .
      docker system prune --force
      docker save chocolatey | split --numeric-suffixes --bytes=2GB - /tmp/build/assets/chocolatey.tar.
      docker rmi chocolatey
      docker system prune --force
      (cd /tmp/build/assets && md5sum chocolatey.tar.* > chocolatey.tar.md5.txt)
      EOF
  - name: msys2
    stage: tar-2
    script: |
      "${m_python3_path}" "${m_tools_directory_path}/travis_wait_alternative.py" sh -e << EOF
      export PS4="executing command: "; set -x
      test -n "${m_git_tag}"
      (cd /tmp/build/output && sh -xe "${m_tools_directory_path}/download-tar.sh" "https://github.com/p5-vbnekit/docker-common-windows-compilers/releases/download/${m_git_tag}" "chocolatey") | docker load
      docker build --tag msys2 --file msys2.Dockerfile .
      docker system prune --force
      docker save msys2 | split --numeric-suffixes --bytes=2GB - /tmp/build/assets/msys2.tar.
      docker rmi msys2 chocolatey
      docker system prune --force
      (cd /tmp/build/assets && md5sum msys2.tar.* > msys2.tar.md5.txt)
      EOF
  - name: chocolatey
    stage: xz
    script: |
      "${m_python3_path}" "${m_tools_directory_path}/travis_wait_alternative.py" sh -e << EOF
      export PS4="executing command: "; set -x
      test -n "${m_git_tag}"
      (cd /tmp/build/output && sh -xe "${m_tools_directory_path}/download-tar.sh" "https://github.com/p5-vbnekit/docker-common-windows-compilers/releases/download/${m_git_tag}" "chocolatey") | "${m_tools_directory_path}/xz.exe" -9 | split --numeric-suffixes --bytes=2GB - /tmp/build/assets/chocolatey.tar.xz.
      (cd /tmp/build/assets && md5sum chocolatey.tar.xz.* > chocolatey.tar.xz.md5.txt)
      EOF
  - name: msys2
    stage: xz
    script: |
      "${m_python3_path}" "${m_tools_directory_path}/travis_wait_alternative.py" sh -e << EOF
      export PS4="executing command: "; set -x
      test -n "${m_git_tag}"
      (cd /tmp/build/output && sh -xe "${m_tools_directory_path}/download-tar.sh" "https://github.com/p5-vbnekit/docker-common-windows-compilers/releases/download/${m_git_tag}" "msys2") | "${m_tools_directory_path}/xz.exe" -9 | split --numeric-suffixes --bytes=2GB - /tmp/build/assets/msys2.tar.xz.
      (cd /tmp/build/assets && md5sum msys2.tar.xz.* > msys2.tar.xz.md5.txt)
      EOF
